apiVersion: v2
name: workbook
description: workbook db service

type: application

version: 0.1.0


dependencies:
  - name: workbook-lib
    version: "0.4.1"
    repository: "https://charts.semafor.ch"
