image:
  repository: ghcr.io/semaforinformatik/workbook
  pullPolicy: IfNotPresent
  tag: "3.4"

nameOverride: ""
fullnameOverride: ""

datasource:
  url: jdbc:h2:file:/tmp/db/data
  username: user
  password: pass

metrics:
  enabled: false

otel:
  enabled: false
  # endpoint:

oidc:
  enabled: false
  # issuer:
  # client:
  # clientSecret:
  # certificates:
